version: '3.8'
services:
  php:
    image: netyji_facturx_pdf:php8.3
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./app:/app
    working_dir: /app
    user: 1000:1000