services:
  web:
    image: nginx:1.25.3
    container_name: nginx
    ports:
      - '${NGINX_PORT:-80}:80'
    volumes:
      - ./app:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
      - mysql
    depends_on:
      - php
      - mysql
  node:
    image: node:20.10-alpine
    volumes:
      - ./app:/app
    container_name: node
    working_dir: /app
    tty: true
    user: 1000:1000
    ports:
      - 5173:5173
  php:
    image: netyji_solution:php8.3
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    container_name: php
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ./app:/app
    links:
      - mysql
    depends_on:
      - mysql
    working_dir: /app
    user: 1000:1000
  mysql:
    image: mysql:8.2.0
    container_name: mysql
    command: ['--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - '${MYSQL_PORT:-3306}:3306'
    volumes:
      - ./database:/var/lib/mysql
    user: 1000:1000
  mailpit:
    image: axllent/mailpit:v1.10.4
    container_name: mailpit
    volumes:
      - ./mail:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
